### ISSUE TITLE
geoip2 module

### ISSUE THREAD

**Issue by re-thc** [hakasenyang/nginx-build#2]
Hi, possible to use the geoip2 module instead of geoip? geoip is the legacy database and geoip2 is the newer 1. https://github.com/leev/ngx_http_geoip2_module

Thanks!

**Comment by hakasenyang** [comment]
Hello.

Yes. I will proceed to update the README and GeoIP2 within two days. 👍

**Comment by hakasenyang** [comment]
Updated.
Check - https://github.com/hakasenyang/nginx-build/commit/208765973a8b816659ae457b1e6f76631d8b690c

**Comment by hakasenyang** [comment]
Close the issue because there are no other issues.
