### ISSUE TITLE
Cipher issues

### ISSUE THREAD

**Issue by re-thc** [hakasenyang/nginx-build#3]
Hi, as per https://www.ssllabs.com/ssltest/analyze.html?d=ssl.hakase.io

Chrome 69 / Win 7  R | Protocol or cipher suite mismatch0x7f1c  \|  TLS_AES_128_GCM_SHA256
Firefox 62 / Win 7  R | Protocol or cipher suite mismatch0x7f1c  \|  TLS_AES_128_GCM_SHA256
TLS_RSA_WITH_AES_128_CBC_SHA (0x2f)   WEAK
TLS_RSA_WITH_AES_256_CBC_SHA (0x35)   WEAK
TLS_RSA_WITH_3DES_EDE_CBC_SHA (0xa)   WEAK

Are you able to fix these? Thanks.

**Comment by hakasenyang** [comment]
SSLLabs only supports TLS 1.3 final.

WEAK Cipher is turned on for compatibility. If you want, please set ssl_protocols to TLSv1.2 TLSv1.3.

**Comment by re-thc** [comment]
Does this address the Protocol or cipher suite mismatch issues? Weak cipher is ok.

**Comment by hakasenyang** [comment]
There are no issues connecting from a real browser. It's just a problem that can not be tested in SSLLabs.

Cloudflare also supports drafts 23, 28, and final, but SSLLabs has the same issue.

**Comment by re-thc** [comment]
Ok thanks
